// Hippo Clinic — PDF builder.
//
// Server-side PDF generation for clinic letters, full notes, and patient
// instructions. We use `pdfkit` because it produces real, selectable text
// PDFs (no rasterised pages), runs on Node serverless, and has no native
// dependencies — important for Vercel cold-starts.
//
// All PDFs are watermarked "Generated via Hippo Clinic — clinician must
// verify accuracy" so a stray printout still carries the clinical-review
// caveat. The watermark is faint grey, not red, so it does not look like
// an alert.

import PDFDocument from "pdfkit";
import { Readable } from "node:stream";

interface BuildLetterArgs {
  clinicianName: string;
  clinicianRole?: string;
  clinicianSpecialty?: string;
  institutionLine?: string;
  patientName?: string;
  encounterDate: Date;
  visitReason?: string;
  body: string; // The letter body (paragraphs, salutation, sign-off).
  variant: "letter" | "note" | "instructions";
}

const MARGIN = 64; // ~22mm

export async function buildClinicPdf(args: BuildLetterArgs): Promise<Buffer> {
  const doc = new PDFDocument({
    size: "LETTER",
    margins: { top: MARGIN, bottom: MARGIN, left: MARGIN, right: MARGIN },
    info: {
      Title:
        args.variant === "letter"
          ? `Clinic letter — ${args.patientName ?? "patient"}`
          : args.variant === "instructions"
          ? `Patient instructions — ${args.patientName ?? "patient"}`
          : `Clinic note — ${args.patientName ?? "patient"}`,
      Author: args.clinicianName,
      Producer: "Hippo Clinic",
      Creator: "Hippo Clinic",
    },
  });

  // Collect bytes.
  const chunks: Buffer[] = [];
  doc.on("data", (b) => chunks.push(b as Buffer));
  const done = new Promise<Buffer>((resolve) => doc.on("end", () => resolve(Buffer.concat(chunks))));

  // ── Header ──────────────────────────────────────────────────────────────
  doc
    .font("Helvetica-Bold")
    .fontSize(11)
    .fillColor("#0f172a")
    .text("Hippo Clinic", { continued: false });
  doc
    .font("Helvetica")
    .fontSize(8)
    .fillColor("#64748b")
    .text(
      args.encounterDate.toLocaleDateString("en-CA", {
        year: "numeric",
        month: "long",
        day: "numeric",
      }),
    );
  if (args.institutionLine) {
    doc.text(args.institutionLine);
  }
  doc.moveDown(1.5);

  // ── Title ───────────────────────────────────────────────────────────────
  const title =
    args.variant === "letter"
      ? "Clinic letter"
      : args.variant === "instructions"
      ? "Patient instructions"
      : "Clinic note";
  doc
    .font("Helvetica-Bold")
    .fontSize(16)
    .fillColor("#0f172a")
    .text(title);
  if (args.patientName) {
    doc
      .moveDown(0.2)
      .font("Helvetica")
      .fontSize(10)
      .fillColor("#475569")
      .text(`Patient: ${args.patientName}`);
  }
  if (args.visitReason) {
    doc.text(`Reason: ${args.visitReason}`);
  }
  doc.moveDown(1);

  // ── Body ────────────────────────────────────────────────────────────────
  doc.font("Helvetica").fontSize(11).fillColor("#0f172a");
  // pdfkit handles wrapping for `text()` automatically. We split paragraphs
  // ourselves so blank lines render as proper spacing.
  const paragraphs = args.body.split(/\n{2,}/);
  for (const p of paragraphs) {
    doc.text(p, { align: "left", lineGap: 2 });
    doc.moveDown(0.6);
  }

  // ── Watermark / disclaimer ─────────────────────────────────────────────
  // Footer on every page. We add it AFTER the body so any pages added by
  // text wrapping get caught when we iterate.
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    const bottom = doc.page.height - MARGIN + 24;
    doc
      .font("Helvetica-Oblique")
      .fontSize(8)
      .fillColor("#94a3b8")
      .text(
        "Generated by Hippo Clinic — clinician must verify accuracy. Not a final medical record without clinician review.",
        MARGIN,
        bottom,
        { width: doc.page.width - MARGIN * 2, align: "center" },
      );
  }

  doc.end();
  return done;
}

/** Convenience: pipe the buffer into a Web Response stream. */
export function pdfResponse(buffer: Buffer, filename: string): Response {
  // pdfkit returns a Node Buffer; we re-wrap as a Uint8Array for the Web
  // Response constructor. The filename gets ASCII-sanitised so RFC 6266 is
  // happy with our headers.
  const stream = Readable.from(buffer);
  return new Response(stream as unknown as ReadableStream, {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${sanitizeFilename(filename)}.pdf"`,
      "Cache-Control": "private, no-store",
    },
  });
}

function sanitizeFilename(name: string): string {
  return name.replace(/[^A-Za-z0-9._-]+/g, "_").slice(0, 120) || "clinic-letter";
}
