export const metadata = { title: "Terms of Use · Hippo" };

export default function TermsPage() {
  return (
    <>
      <h1 style={{ fontSize: 28, fontWeight: 700, color: "var(--text, #f4f4f5)", letterSpacing: "-.4px", marginBottom: 6 }}>Terms of Use</h1>
      <p style={{ fontSize: 12, color: "var(--text-3, #71717a)", marginBottom: 28 }}>Effective date: 2026-04-14</p>

      <h2 style={H2}>1. Not an official record</h2>
      <p>Hippo is a personal productivity tool. It is not certified, endorsed by, or integrated with the ACGME, the Royal College of Physicians and Surgeons of Canada, or any other accreditation body unless a specific written agreement exists with your institution. You are solely responsible for maintaining your official training record in the system your program specifies.</p>

      <h2 style={H2}>2. Not medical advice or billing guidance</h2>
      <p>Content generated by Hippo (briefs, debriefs, procedure suggestions, dictation drafts, AI-generated commentary) is an educational aid for licensed clinicians. It is not medical advice, not diagnostic, not a substitute for clinical judgment, and not a coding/billing determination. Verify every output against primary sources.</p>

      <h2 style={H2}>3. Your account</h2>
      <p>You are responsible for your credentials, for not sharing your account, and for the accuracy of what you enter. Do not enter identifiable patient information.</p>

      <h2 style={H2}>4. Acceptable use</h2>
      <ul>
        <li>No direct patient identifiers in any field.</li>
        <li>No uploading images containing identifiable patient information.</li>
        <li>No scraping, reverse-engineering, or abusive use of the API.</li>
        <li>No impersonating another clinician or misrepresenting a sign-off.</li>
      </ul>

      <h2 style={H2}>5. Attending sign-offs</h2>
      <p>Attending-generated sign-offs in Hippo are attestations by the attending. They are offered as a personal record for the resident. They are not a substitute for your program&apos;s official evaluation system unless your program has adopted Hippo as its record of truth in writing.</p>

      <h2 style={H2}>6. Fees & cancellation</h2>
      <p>Paid plans (Pro, Institution) are billed by Stripe. You can cancel at any time from Settings; cancellation stops future renewals but does not refund the current period unless required by law. We may change pricing with 30 days&apos; notice.</p>

      <h2 style={H2}>7. Termination</h2>
      <p>We may suspend accounts that violate these terms or pose a security risk. You can delete your account at any time from Settings.</p>

      <h2 style={H2}>8. Warranty & liability</h2>
      <p>Hippo is provided &quot;as is&quot; without warranty. To the maximum extent permitted by law, our total liability for any claim is limited to the amount you paid us in the twelve months prior to the claim.</p>

      <h2 style={H2}>9. Governing law</h2>
      <p>These terms are governed by the laws of Manitoba, Canada. Disputes will be resolved in the courts of Manitoba.</p>

      <h2 style={H2}>10. Contact</h2>
      <p><a href="mailto:legal@hippomedicine.com" style={A}>legal@hippomedicine.com</a></p>
    </>
  );
}

const H2 = { fontSize: 17, fontWeight: 600, color: "var(--text, #f4f4f5)", marginTop: 28, marginBottom: 10 };
const A = { color: "#3b82f6", textDecoration: "none" };
