export const metadata = { title: "Terms of Use · Hippo" };

export default function TermsPage() {
  return (
    <>
      <h1 style={{ fontSize: 28, fontWeight: 700, color: "var(--text, #f4f4f5)", letterSpacing: "-.4px", marginBottom: 6 }}>
        Terms of Use
      </h1>
      <p style={{ fontSize: 12, color: "var(--text-3, #71717a)", marginBottom: 28 }}>
        Effective date: 2026-04-17 · Last updated: 2026-04-17
      </p>

      <p style={{ marginBottom: 18 }}>
        These Terms of Use (the &ldquo;Terms&rdquo;) govern your access to and use of the Hippo
        platform provided by Hippo Medicine Inc. (&ldquo;Hippo&rdquo;, &ldquo;we&rdquo;,
        &ldquo;us&rdquo;). They sit alongside the{" "}
        <a href="/legal/eula" style={A}>EULA</a>, the{" "}
        <a href="/legal/privacy" style={A}>Privacy Policy</a>, the{" "}
        <a href="/legal/phia" style={A}>PHIA Notice</a>, and the{" "}
        <a href="/legal/acceptable-use" style={A}>Acceptable Use Policy</a>. By creating an account,
        signing in, or using any Hippo feature, you agree to be bound by these Terms. If you do not
        agree, do not use the platform.
      </p>

      <h2 style={H2}>1. Not an official training record</h2>
      <p>
        Hippo is a personal productivity tool. It is <strong>not certified, endorsed by, or
        integrated with</strong> the Royal College of Physicians and Surgeons of Canada (RCPSC),
        the Accreditation Council for Graduate Medical Education (ACGME), any residency program,
        medical school, hospital, regulator, licensing college, or professional body, unless a
        specific written agreement exists with your institution. You are solely responsible for
        maintaining your official training record in the system your program specifies.
      </p>

      <h2 style={H2}>2. Not medical, billing, legal, or privacy advice</h2>
      <p>
        Content generated by Hippo &mdash; briefs, debriefs, procedure suggestions, EPA suggestions,
        O-score recommendations, dictation drafts, AI-generated commentary, or any other output
        &mdash; is an educational aid for licensed clinicians. It is not medical advice, not
        diagnostic, not a substitute for clinical judgment, not a coding or billing determination,
        not legal advice, and not privacy-compliance advice. Verify every output against primary
        sources, your institutional policies, and your own professional judgment before relying on
        it.
      </p>

      <h2 style={H2}>3. AI disclaimer and no reliance</h2>
      <p>
        Several Hippo features use artificial-intelligence models hosted by third parties (currently
        Google and Groq; see the <a href="/legal/phia" style={A}>PHIA Notice §4</a> for the
        current provider list and the <a href="/legal/subprocessors" style={A}>Subprocessors</a>{" "}
        page for the operational list). AI outputs may be <strong>incomplete, inaccurate,
        misleading, biased, fabricated, outdated, or otherwise not fit for any particular
        purpose</strong>. They are provided for drafting, educational, and workflow-support
        purposes only.
      </p>
      <p>
        You are solely responsible for reviewing, verifying, editing, and approving every AI
        output before any clinical, educational, administrative, regulatory, legal, research,
        billing, or public use. You agree that you will not rely on AI output as authoritative and
        that you remain the accountable decision-maker for any action taken in reference to an AI
        output.
      </p>

      <h2 style={H2}>4. Your account</h2>
      <p>
        You are responsible for your credentials, for maintaining their confidentiality, for all
        activity under your account, for not sharing access with anyone else, and for the accuracy
        of information you provide. You must notify us immediately at{" "}
        <a href="mailto:legal@hippomedicine.com" style={A}>legal@hippomedicine.com</a> of any
        unauthorized access or suspected compromise. We may suspend access to investigate credential
        abuse or security events.
      </p>

      <h2 style={H2}>5. User content &mdash; warranty and responsibility</h2>
      <p>
        You are solely responsible for all content you upload, submit, generate, post, transmit,
        dictate, voice-log, import, or share through the platform (&ldquo;Your Content&rdquo;). You
        represent and warrant that Your Content:
      </p>
      <ul>
        <li>is lawful in every jurisdiction from which you submit or access it;</li>
        <li>
          does <strong>not</strong> contain personal health information, patient identifiers,
          confidential information, trade secrets, or other regulated data except where you are
          explicitly legally authorized to provide it AND your use fully complies with all
          applicable law, institutional policy, and professional obligations;
        </li>
        <li>
          does <strong>not</strong> violate PHIA (Manitoba), PIPEDA, HIPAA, any other Canadian,
          U.S., or foreign privacy legislation, your duty of confidentiality, hospital or university
          policy, employment or training-program obligations, or any third party&rsquo;s rights
          (including intellectual-property and privacy rights);
        </li>
        <li>
          is accurate and not intended to impersonate another clinician or misrepresent a sign-off,
          entrustment decision, or evaluation;
        </li>
        <li>
          is yours to provide, or that you have all rights, licences, and consents necessary to
          provide it and to grant Hippo the operational licence below.
        </li>
      </ul>
      <p>
        You grant Hippo a worldwide, non-exclusive, royalty-free licence to host, store, transmit,
        display, de-identify, aggregate, analyse, and process Your Content solely to operate and
        improve the platform, comply with legal obligations, and provide the features you use. You
        retain all other rights in Your Content.
      </p>

      <h2 style={H2}>6. Privacy-specific user promises (no PHI)</h2>
      <p>
        Canadian privacy guidance emphasizes that de-identification is contextual and imperfect.
        Accordingly you expressly confirm that you will <strong>not</strong> upload, enter, dictate,
        or otherwise submit any of the following into any Hippo field &mdash; AI-facing or
        otherwise:
      </p>
      <ul>
        <li>patient names (first, last, preferred, nickname, initials combined with other identifiers);</li>
        <li>full or partial dates of birth;</li>
        <li>medical record numbers, health-card numbers, chart numbers, OR-schedule numbers;</li>
        <li>exact dates of service, exact times of service, or date + facility combinations;</li>
        <li>
          hospital, clinic, or unit identifiers combined with other quasi-identifiers that could
          re-identify a patient;
        </li>
        <li>facial images, tattoos, distinguishing physical features, or other biometric identifiers;</li>
        <li>
          free-text detail &mdash; including rare diagnoses, small-cell demographics, or unusual
          timing &mdash; that a reasonable third party could combine with other information to
          re-identify a patient;
        </li>
        <li>
          credentials, API keys, access tokens, passwords, or any security material belonging to you
          or to a third party.
        </li>
      </ul>
      <p>
        If you believe you are required to enter any of the above to use Hippo, <strong>stop and
        consult your institution&rsquo;s privacy officer first</strong>. The existence of this rule
        does not create an obligation on Hippo to police every submission; enforcement is a shared
        responsibility and the automated scrubbing described in the{" "}
        <a href="/legal/phia" style={A}>PHIA Notice</a> is defense-in-depth, not a guarantee.
      </p>

      <h2 style={H2}>7. Acceptable use</h2>
      <p>In addition to §5 and §6, you agree you will not:</p>
      <ul>
        <li>upload images or files that contain identifiable patient information of any form;</li>
        <li>scrape, reverse-engineer, probe, decompile, or abuse the API or scrape data rate-limits;</li>
        <li>
          impersonate another clinician, misrepresent a sign-off, fabricate an entrustment decision,
          or alter records to misstate your training experience;
        </li>
        <li>use the platform for activities unlawful in your jurisdiction;</li>
        <li>interfere with other users, introduce malware, or bypass security controls;</li>
        <li>
          train, fine-tune, or distill a machine-learning model on Hippo outputs or platform content
          without our written consent.
        </li>
      </ul>
      <p>
        See the <a href="/legal/acceptable-use" style={A}>Acceptable Use Policy</a> for the complete
        list.
      </p>

      <h2 style={H2}>8. Attending sign-offs</h2>
      <p>
        Attending-generated sign-offs in Hippo are personal attestations by the attending, offered
        as a record for the resident. They are <strong>not</strong> a substitute for your
        program&rsquo;s official evaluation system unless your program has adopted Hippo as its
        record of truth in writing. Do not rely on a Hippo sign-off for licensure, graduation, or
        any other accreditation-facing use unless your program has told you, in writing, to do so.
      </p>

      <h2 style={H2}>9. Professional-use restriction</h2>
      <p>
        You are individually responsible for ensuring your use of Hippo complies with the rules of
        your licensing regulator, medical college, hospital, university, residency or fellowship
        program, health authority, and any applicable privacy legislation. We make no warranty that
        the platform is suitable for use in any specific professional or regulatory context. It is
        your obligation &mdash; not ours &mdash; to confirm fit with your institutional policies
        before using the platform for any professional purpose.
      </p>

      <h2 style={H2}>10. Content moderation and platform integrity</h2>
      <p>
        We reserve the unrestricted right, at our sole discretion and without prior notice, to:
      </p>
      <ul>
        <li>
          remove, redact, suspend, quarantine, investigate, preserve, or disclose Your Content or
          any other content hosted on the platform where we reasonably believe it is necessary for
          safety, privacy, security, legal compliance, law-enforcement cooperation, platform
          integrity, or enforcement of these Terms;
        </li>
        <li>
          suspend, limit, or terminate an account that violates these Terms, poses a security risk,
          is implicated in suspected PHI leakage, or is subject to a credible complaint from a third
          party;
        </li>
        <li>
          cooperate with lawful requests from courts, regulators, or privacy commissioners, including
          producing account data and content as required.
        </li>
      </ul>
      <p>
        Use of these rights does not create any obligation on Hippo to monitor content proactively
        or to take action in any particular case.
      </p>

      <h2 style={H2}>11. Indemnification</h2>
      <p>
        To the maximum extent permitted by law, you agree to defend, indemnify, and hold harmless
        Hippo Medicine Inc., its founder, officers, directors, shareholders, employees, contractors,
        agents, affiliates, successors, and assigns (the &ldquo;Indemnified Parties&rdquo;) from and
        against any and all claims, complaints, investigations, proceedings, actions, damages,
        losses, liabilities, settlements, judgments, regulatory penalties or fines, costs, and
        expenses &mdash; including reasonable legal fees on a solicitor-and-own-client basis
        &mdash; arising out of or related to:
      </p>
      <ul>
        <li>Your Content, including any PHI, patient identifiers, or confidential material you submit;</li>
        <li>your use, reliance on, or distribution of any AI output generated through the platform;</li>
        <li>your breach of these Terms, any representation or warranty, or any other agreement with Hippo;</li>
        <li>
          your violation of any applicable law, privacy legislation, confidentiality duty,
          professional obligation, institutional policy, or third-party right;
        </li>
        <li>any misrepresentation regarding your identity, role, credentials, or authorization to use the platform.</li>
      </ul>
      <p>
        We reserve the right, at our own expense, to assume the exclusive defence and control of any
        matter otherwise subject to indemnification by you, in which case you agree to cooperate
        with our defence. You will not settle any claim that affects the Indemnified Parties without
        our prior written consent.
      </p>

      <h2 style={H2}>12. Warranty disclaimer</h2>
      <p>
        The platform is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis,
        with all faults. <strong>To the maximum extent permitted by law, Hippo disclaims all
        warranties, express or implied</strong>, including without limitation warranties of
        merchantability, fitness for a particular purpose, non-infringement, quiet enjoyment,
        accuracy, completeness, timeliness, uninterrupted operation, security, or that defects will
        be corrected. No oral or written information or advice given by Hippo or its personnel
        creates a warranty.
      </p>

      <h2 style={H2}>13. Limitation of liability</h2>
      <p>
        <strong>To the maximum extent permitted by law, Hippo and the Indemnified Parties will not
        be liable for any indirect, incidental, special, consequential, exemplary, or punitive
        damages</strong>, or for any loss of data, profits, revenue, goodwill, business opportunity,
        reputation, regulatory standing, or training progress, whether arising in contract, tort,
        negligence, strict liability, statute, or any other theory, and regardless of whether Hippo
        was advised of the possibility of such damages.
      </p>
      <p>
        To the maximum extent permitted by law, Hippo&rsquo;s aggregate liability to you arising out
        of or related to the platform or these Terms shall not exceed the <strong>greater of (a) the
        fees you paid to Hippo in the twelve months immediately preceding the event giving rise to
        the claim, or (b) one hundred Canadian dollars (CAD $100)</strong>. This cap applies on a
        per-user basis and is cumulative across all claims.
      </p>
      <p>
        These limitations form an essential basis of the bargain between you and Hippo. Some
        jurisdictions do not allow the exclusion of certain warranties or the limitation of
        liability for consequential or incidental damages; in such jurisdictions the foregoing
        limitations apply to the greatest extent permitted.
      </p>

      <h2 style={H2}>14. Fees and cancellation</h2>
      <p>
        The platform is currently provided free of charge during an open-beta period. If we
        introduce paid plans in the future, we will give you reasonable advance notice and you will
        have the opportunity to decline and export your data before any charge. We may change
        pricing for future billing cycles with at least 30 days&rsquo; notice.
      </p>

      <h2 style={H2}>15. Termination</h2>
      <p>
        You may delete your account at any time from Settings &rarr; Account, which immediately and
        permanently deletes Your Content as described in the{" "}
        <a href="/legal/privacy" style={A}>Privacy Policy</a>. We may suspend or terminate accounts
        that violate these Terms, pose a security or privacy risk, or are dormant for an extended
        period, with or without notice. Sections that by their nature should survive termination
        &mdash; including §§5, 6, 9, 11, 12, 13, 16, and 17 &mdash; survive.
      </p>

      <h2 style={H2}>16. Governing law and dispute resolution</h2>
      <p>
        These Terms are governed by the laws of the Province of Manitoba and the federal laws of
        Canada applicable therein, without regard to conflict-of-laws rules. The parties submit to
        the exclusive jurisdiction of the courts of Manitoba for any dispute arising under these
        Terms. You waive any objection to venue or forum non conveniens in those courts.
      </p>

      <h2 style={H2}>17. Changes to these Terms</h2>
      <p>
        We may update these Terms from time to time. When we do, we will update the &ldquo;Effective
        date&rdquo; above and, for material changes, require you to re-accept the updated Terms
        before continuing to use the platform. Continued use of the platform after the effective
        date of a revision constitutes acceptance.
      </p>

      <h2 style={H2}>18. Miscellaneous</h2>
      <p>
        These Terms, together with the EULA, Privacy Policy, PHIA Notice, and Acceptable Use Policy,
        constitute the entire agreement between you and Hippo concerning the platform. If any
        provision is held unenforceable, the remaining provisions remain in full force. Our failure
        to enforce any right is not a waiver of that right. You may not assign these Terms without
        our written consent; we may assign them in connection with a merger, acquisition, or sale of
        substantially all assets.
      </p>

      <h2 style={H2}>19. Contact</h2>
      <p>
        Questions, notices, or requests related to these Terms:{" "}
        <a href="mailto:legal@hippomedicine.com" style={A}>legal@hippomedicine.com</a>.
      </p>

      <p style={{ fontSize: 12, color: "var(--text-3, #71717a)", marginTop: 32 }}>
        These Terms summarize Hippo&rsquo;s legal position. They are not legal advice to you. If you
        are uncertain about how they apply to your circumstances, consult your own lawyer.
      </p>
    </>
  );
}

const H2 = { fontSize: 17, fontWeight: 600, color: "var(--text, #f4f4f5)", marginTop: 28, marginBottom: 10 };
const A = { color: "#3b82f6", textDecoration: "none" };
