import { NextRequest, NextResponse } from "next/server";
import PDFDocument from "pdfkit";
import { requireAuth } from "@/lib/api-auth";
import { loadProgramCommandCenter } from "@/lib/pd-command-center/load";

export const runtime = "nodejs";

export async function GET(request: NextRequest) {
  const auth = await requireAuth();
  if (auth.error) return auth.error;
  const programId = request.nextUrl.searchParams.get("programId");
  const data = await loadProgramCommandCenter(auth.user.id, programId);
  if (!data) return NextResponse.json({ error: "Program owner access required." }, { status: 403 });

  const doc = new PDFDocument({ size: "LETTER", margin: 48, info: { Title: `${data.program.name} pilot report`, Author: "Hippo Medicine" } });
  const chunks: Buffer[] = [];
  doc.on("data", (chunk: Buffer) => chunks.push(chunk));
  const complete = new Promise<Buffer>((resolve, reject) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });

  doc.rect(0, 0, doc.page.width, 104).fill("#07110f");
  doc.fillColor("#77e2ba").fontSize(10).font("Helvetica-Bold").text("HIPPO MEDICINE · PROGRAM PILOT", 48, 34);
  doc.fillColor("#ffffff").fontSize(22).text(data.program.name, 48, 53);
  doc.fillColor("#b7c8c2").fontSize(9).font("Helvetica").text(`${data.program.institution} · ${data.program.specialty} · Day ${data.program.pilotDay} of ${data.program.pilotLengthDays}`, 48, 82);

  doc.fillColor("#10211b").font("Helvetica-Bold").fontSize(16).text("Executive summary", 48, 132);
  doc.font("Helvetica").fontSize(10).fillColor("#53645e").text(data.weeklyBrief.headline, 48, 158);
  doc.text(data.weeklyBrief.summary, 48, 176);
  let y = 210;
  for (const bullet of data.weeklyBrief.bullets) {
    doc.fillColor("#087a55").circle(52, y + 4, 2).fill();
    doc.fillColor("#33443e").text(bullet, 62, y, { width: 480 });
    y += 20;
  }

  const metrics = [
    ["Cases · 30 days", String(data.metrics.cases30)],
    ["Resident adoption", `${data.metrics.adoptionPercent}%`],
    ["EPA completion", `${data.metrics.epaCompletionPercent}%`],
    ["Pending sign-offs", String(data.metrics.pendingSignoffs)],
  ];
  y += 12;
  metrics.forEach(([label, value], index) => {
    const x = 48 + index * 126;
    doc.roundedRect(x, y, 112, 62, 3).fillAndStroke("#f1f5f2", "#d7e0db");
    doc.fillColor("#087a55").font("Helvetica-Bold").fontSize(18).text(value, x + 10, y + 11);
    doc.fillColor("#61716a").font("Helvetica").fontSize(7).text(label.toUpperCase(), x + 10, y + 39, { width: 92 });
  });

  y += 92;
  doc.fillColor("#10211b").font("Helvetica-Bold").fontSize(16).text("Cohort signals", 48, y);
  y += 28;
  if (!data.alerts.length) {
    doc.fillColor("#087a55").font("Helvetica").fontSize(10).text("No urgent program signals at the time of this report.", 48, y);
    y += 24;
  } else {
    for (const alert of data.alerts.slice(0, 6)) {
      doc.fillColor(alert.level === "critical" ? "#b42318" : "#9a6700").font("Helvetica-Bold").fontSize(9).text(alert.title, 48, y);
      doc.fillColor("#61716a").font("Helvetica").text(alert.detail, 190, y, { width: 360 });
      y += 18;
    }
  }

  y += 16;
  doc.fillColor("#10211b").font("Helvetica-Bold").fontSize(16).text("Resident pulse", 48, y);
  y += 26;
  doc.fillColor("#61716a").fontSize(8).text("Resident", 48, y).text("Year", 235, y).text("Cases (30d)", 320, y).text("EPAs", 405, y).text("Signal", 480, y);
  y += 14;
  doc.moveTo(48, y).lineTo(564, y).strokeColor("#d7e0db").stroke();
  y += 8;
  for (const resident of data.residents.slice(0, 12)) {
    if (y > 720) { doc.addPage(); y = 54; }
    doc.fillColor("#10211b").font("Helvetica-Bold").fontSize(8).text(resident.name, 48, y, { width: 175 });
    doc.fillColor("#61716a").font("Helvetica").text(resident.trainingYear, 235, y).text(String(resident.cases30), 320, y).text(`${resident.epaSigned}/${resident.epaTotal}`, 405, y).text(resident.signal === "good" ? "On track" : resident.signal === "watch" ? "Watch" : "Action", 480, y);
    y += 17;
  }

  doc.fontSize(7).fillColor("#82918a").text("Program-scoped training information only. This report contains no patient identifiers. Generated by Hippo Medicine.", 48, 744, { width: 516, align: "center" });
  doc.end();

  const pdf = await complete;
  const safeName = data.program.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  return new NextResponse(new Uint8Array(pdf), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${safeName}-pilot-report.pdf"`,
      "Cache-Control": "private, no-store",
    },
  });
}
